# Generated by Django 3.2.9 on 2021-12-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_with_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена со скидкой'),
        ),
    ]
